name: Build and Deploy
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o dist/validate-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -v -o dist/validate-linux-arm64 .

          GOOS=darwin GOARCH=amd64 go build -v -o dist/validate-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -v -o dist/validate-darwin-arm64 .
          
          GOOS=windows GOARCH=amd64 go build -v -o dist/validate-windows-amd64.exe .
          GOOS=windows GOARCH=arm64 go build -v -o dist/validate-windows-arm64.exe .

          chmod +x dist/*

      - name: Test
        run: go test -v ./...

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Zip
        run: |
          cd dist
          
          zip validate-linux-amd64.zip validate-linux-amd64
          zip validate-linux-arm64.zip validate-linux-arm64

          zip validate-darwin-amd64.zip validate-darwin-amd64
          zip validate-darwin-arm64.zip validate-darwin-arm64
          
          zip validate-windows-amd64.zip validate-windows-amd64.exe
          zip validate-windows-arm64.zip validate-windows-arm64.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}